/*
  Auto-generated by Spline
*/

import useSpline from "@splinetool/r3f-spline";
import { OrthographicCamera } from "@react-three/drei";

export default function Scene({ ...props }) {
	const { nodes, materials } = useSpline(
		"https://prod.spline.design/Luj0x6qGCNfBLyrh/scene.splinecode"
	);
	return (
		<>
			<color attach="background" args={["#3e3e3e"]} />
			<group {...props} dispose={null}>
				<scene name="Scene">
					<directionalLight
						name="Directional Light 3"
						castShadow
						intensity={0.7}
						shadow-mapSize-width={1024}
						shadow-mapSize-height={1024}
						shadow-camera-near={-10000}
						shadow-camera-far={100000}
						shadow-camera-left={-1000}
						shadow-camera-right={1000}
						shadow-camera-top={1000}
						shadow-camera-bottom={-1000}
						position={[672.65, -496.68, 300]}
					/>
					<OrthographicCamera
						name="Camera"
						makeDefault={true}
						zoom={0.81}
						far={100000}
						near={-100000}
						up={[0, 1, 0]}
						position={[131.1, 319.07, 1193.55]}
						rotation={[-0.15, 0.24, 0.04]}
					/>
					<directionalLight
						name="Directional Light 2"
						castShadow
						intensity={0.7}
						shadow-mapSize-width={1024}
						shadow-mapSize-height={1024}
						shadow-camera-near={-10000}
						shadow-camera-far={100000}
						shadow-camera-left={-1000}
						shadow-camera-right={1000}
						shadow-camera-top={1000}
						shadow-camera-bottom={-1000}
						position={[-1549.06, -200.46, 300]}
					/>
					<group
						name="Group"
						position={[-137.67, 147.36, 195.06]}
						rotation={[0, 0.24, 0]}
					>
						<mesh
							name="Icosahedron"
							geometry={nodes.Icosahedron.geometry}
							material={materials["Icosahedron Material"]}
							castShadow
							receiveShadow
							position={[0, 0, 0]}
							scale={1.1}
						/>
						<mesh
							name="Sphere"
							geometry={nodes.Sphere.geometry}
							material={materials["Sphere Material"]}
							castShadow
							receiveShadow
							position={[4.26, -19.03, -7.59]}
						/>
					</group>
					<directionalLight
						name="Directional Light"
						castShadow
						intensity={0.7}
						shadow-mapSize-width={1024}
						shadow-mapSize-height={1024}
						shadow-camera-near={-10000}
						shadow-camera-far={100000}
						shadow-camera-left={-1000}
						shadow-camera-right={1000}
						shadow-camera-top={1000}
						shadow-camera-bottom={-1000}
						position={[258.22, 515.54, 300]}
					/>
					<OrthographicCamera
						name="1"
						makeDefault={false}
						far={10000}
						near={-50000}
					/>
					<hemisphereLight
						name="Default Ambient Light"
						intensity={3.35}
						color="#74ebe0"
					/>
				</scene>
			</group>
		</>
	);
}
