export default data = [
	{
		companyName: "Nationwide Building Society",
		dateFrom: "2023",
		dateTo: "Present",
		role: "Software Engineer",
		roleDescription:
			"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam et impedit, laudantium aperiam modi quasi dignissimos recusandae, ducimus excepturi illum voluptatum praesentium at, omnis incidunt illo sunt expedita alias dolor error dolorem beatae maiores minus asperiores? Odit expedita explicabo, minus corporis veritatis soluta doloremque aperiam cum eaque culpa molestias fuga.",
		location: "Remote",
		tech: ["javascript", "react", "node", "css", "html"],
	},
	{
		companyName: "",
		dateFrom: "",
		dateTo: "",
		role: "",
		roleDescription: "",
		location: "",
		tech: [],
	},
	{
		companyName: "",
		dateFrom: "",
		dateTo: "",
		role: "",
		roleDescription: "",
		location: "",
		tech: [],
	},
	{
		companyName: "",
		dateFrom: "",
		dateTo: "",
		role: "",
		roleDescription: "",
		location: "",
		tech: [],
	},
	{
		companyName: "",
		dateFrom: "",
		dateTo: "",
		role: "",
		roleDescription: "",
		location: "",
		tech: [],
	},
];
