import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "@next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/navbar/Navbar";

const poppins = Poppins({ weight: "600", subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en smoot" suppressHydrationWarning={true}>
			<ThemeProvider attribute="class" defaultTheme="system" enableSystem>
				<body className={poppins.className}>
					<Navbar />
					{children}
				</body>
			</ThemeProvider>
		</html>
	);
}
